module.exports = {
    assetsroot: "/assets/",
    catassestspath: "/assets/gyh/images/",
    news_prefix: "//tstdat.to2025.com/upload/up/",
    mode: "dev",
    imgPrefix: "/assets/common/img/",
    jsPrefix: "/assets/common/js/",
    cssPrefix: "/assets/common/css/",
    vendorPrefix: "/assets/common/vendor/",
    gyhjsPrefix: "/assets/gyh/js/",
    gyhImgPrefix: "/assets/gyh/images/",
    gyhcssPrefix: "/assets/gyh/css/",
    gyhpluginsPrefix: "/assets/gyh/plugins/",
    // apiroot: "http://localhost:48734/", 
    // apiroot_v2:"http://localhost:48734/",
    apiroot: "http://www.to2025.cc:919/",
    comfile_prefix: "https://tstdat.to2025.com/upload/cf/",
    proimg:"//tstdat.to2025.com/upload/pic/pp/",
    serimg:"//tstdat.to2025.com/upload/pic/sp/",
    comimg:"//tstdat.to2025.com/upload/pic/cl/",
    userimg:"//tstdat.to2025.com/upload/pic/ap/",
    product_attachment:"//tstdat.to2025.com/upload/att/pa/",
    project_attachment:"//tstdat.to2025.com/upload/att/ja/",
    service_attachment:"//tstdat.to2025.com/upload/att/sa/",
    requirement_attachment:"//tstdat.to2025.com/upload/att/ra/",
    company_attachment:"//tstdat.to2025.com/upload/att/ca/",
    news_attachment:"//tstdat.to2025.com/upload/up/",
    user_attachment: "//tstdat.to2025.com/upload/att/ua/",
    cidep_attachment:"//tstdat.to2025.com/upload/att/cia/",
    banner_pic:"//tstdat.to2025.com/upload/banner/",
    ossImgPrefix: "https://tstres.to2025.com/m2/common/images/",
    posterimg:"https://tstdat.to2025.com/upload/poster/",
    portalapi_root:"http://localhost:48734/",
    title:"to2025.com"
    ,jsVertion:"1",
    portal_root:"http://localhost:11977/",
    login_url:"http://localhost:8085/com/login.html?ref=",
    //login_url:"http://localhost:11977/Common/Login.aspx?ref=",

    QQ_OPEN_WEBAPP_APPID:"101376509",
    QQ_OPEN_WEBAPP_SECRET:"4331475a5259ce76447f0a7ccdf7feef",	
    QQ_OPEN_WEBAPP_RETURNURL:"http://www.to2025.com/Common/QQLoginCallBack.aspx",
    WX_KEY:"zhhlgyh20170331WechatPay125KeyV1",
    WX_OPEN_APPID:"wx5055311880b007d2",
    WX_OPEN_SECRET:"b71988b1cd7c44bec1ce95fd6d25dd18",
    WX_OPEN_WEBAPP_RETURNURL:"http%3A%2F%2Fwww.to2025.com%2Fcommon%2Fwxcallback.aspx",
    
};

