
module.exports = {
    assetsroot: "/assets/",
    catassestspath: "/assets/gyh/images/",
    news_prefix: "//tstdat.to2025.com/upload/up/",
    mode: "pre",
    imgPrefix: "/assets/common/img/",
    jsPrefix: "/assets/common/js/",
    cssPrefix: "/assets/common/css/",
    vendorPrefix: "/assets/common/vendor/",
    gyhjsPrefix: "/assets/gyh/js/",
    gyhcssPrefix: "/assets/gyh/css/",
    gyhpluginsPrefix: "/assets/gyh/plugins/",
    gyhImgPrefix: "/assets/gyh/images/",
    apiroot: "http://www.to2025.cc:919/",
    comfile_prefix: "//tstdat.to2025.com/upload/cf/",
    proimg:"//tstdat.to2025.com/upload/pic/pp/",
    serimg:"//tstdat.to2025.com/upload/pic/sp/",
    comimg:"//tstdat.to2025.com/upload/pic/cl/",
    userimg:"//tstdat.to2025.com/upload/pic/ap/",
    product_attachment:"//tstdat.to2025.com/upload/att/pa/",
    project_attachment:"//tstdat.to2025.com/upload/att/ja/",
    service_attachment:"//tstdat.to2025.com/upload/att/sa/",
    requirement_attachment:"//tstdat.to2025.com/upload/att/ra/",
    company_attachment:"//tstdat.to2025.com/upload/att/ca/",
    news_attachment:"//tstdat.to2025.com/upload/up/",
    user_attachment: "//tstdat.to2025.com/upload/att/ua/",
    cidep_attachment:"//tstdat.to2025.com/upload/att/cia/",
    banner_pic:"//tstdat.to2025.com/upload/banner/",
    ossImgPrefix: "https://tstres.to2025.com/m2/common/images/",
    posterimg:"https://tstdat.to2025.com/upload/poster/",
    title:""
    ,jsVertion:"1",
    portal_root:"http://www.to2025.cc:918/",
    login_url:"http://www.to2025.cc:918/Common/Login.aspx?ref="
};
