
module.exports = {
    assetsroot: "/assets/",
    catassestspath: "/assets/gyh/images/",
    news_prefix: "//dat.to2025.com/upload/up/",
    mode: "pro",
    imgPrefix: "/assets/common/img/",
    jsPrefix: "/assets/common/js/",
    cssPrefix: "/assets/common/css/",
    vendorPrefix: "/assets/common/vendor/",
    gyhjsPrefix: "/assets/gyh/js/",
    gyhcssPrefix: "/assets/gyh/css/",
    gyhpluginsPrefix: "/assets/gyh/plugins/",
    gyhImgPrefix: "/assets/gyh/images/",
    apiroot: "//api.to2025.com/",
    comfile_prefix: "//dat.to2025.com/upload/cf/",
    proimg:"//dat.to2025.com/upload/pic/pp/",
    serimg:"//dat.to2025.com/upload/pic/sp/",
    comimg:"//dat.to2025.com/upload/pic/cl/",
    userimg:"//dat.to2025.com/upload/pic/ap/",
    product_attachment:"//dat.to2025.com/upload/att/pa/",
    project_attachment:"//dat.to2025.com/upload/att/ja/",
    service_attachment:"//dat.to2025.com/upload/att/sa/",
    requirement_attachment:"//dat.to2025.com/upload/att/ra/",
    company_attachment:"//dat.to2025.com/upload/att/ca/",
    news_attachment:"//dat.to2025.com/upload/up/",
    user_attachment: "//dat.to2025.com/upload/att/ua/",
    cidep_attachment:"//dat.to2025.com/upload/att/cia/",
    banner_pic:"//dat.to2025.com/upload/banner/",
    ossImgPrefix: "https://res.to2025.com/m2/common/images/",
    posterimg:"https://dat.to2025.com/upload/poster/",
    title:"",
    jsVertion:"1",
    portal_root:"http://www.to2025.com/",
    login_url:"http://www.to2025.com/Common/Login.aspx?ref="
};
